Fix parsing Z, M, and ZM WKT strings
georust/wkt pull request #115
Opened 2024-07-17 20:06 UTC by kylebarron

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
- [x] I ran cargo fmt
---

2024-07-17 20:10 UTC, kylebarron commented
@michaelkirk since the changes from https://github.com/georust/wkt/pull/110 might be fresh on your mind, do you want to look at the merge conflicts here and/or do you have suggestions for how to resolve them? Or do you want to look at the approach I took here and maybe rebase those onto the latest main?

2024-07-17 20:11 UTC, kylebarron commented
Some of the tests here come from the GEOS test suite in https://github.com/libgeos/geos/blob/8e525c825caf314d61a6279a426a59ded115681e/tests/unit/io/WKTReaderTest.cpp

2024-07-17 20:31 UTC, michaelkirk commented
> @michaelkirk since the changes from https://github.com/georust/wkt/pull/110 might be fresh on your mind, do you want to look at the merge conflicts here and/or do you have suggestions for how to resolve them? Or do you want to look at the approach I took here and maybe rebase those onto the latest main?

Sorry, I wouldn't have merged that if I knew you were working on this. I'll push up a resolution in a moment the changes are pretty mechanical.

2024-07-17 20:42 UTC, michaelkirk commented
I'm seeing some tests failing with your branch. Can you fix those up?

```
failures:

---- tests::empty_items stdout ----
thread 'tests::empty_items' panicked at src/lib.rs:380:63:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::lowercase_point stdout ----
thread 'tests::lowercase_point' panicked at src/lib.rs:395:63:
called `Option::unwrap()` on a `None` value

---- types::multipoint::tests::empty_multipoint stdout ----
thread 'types::multipoint::tests::empty_multipoint' panicked at src/types/multipoint.rs:151:63:
called `Result::unwrap()` on an `Err` value: "Unexpected word before open paren"


failures:
    tests::empty_items
    tests::lowercase_point
```

2024-07-17 21:16 UTC, kylebarron commented
> Sorry, I wouldn't have merged that if I knew you were working on this.

No worries! It was just bad luck!

2024-07-17 23:12 UTC, kylebarron commented
tests all pass locally now!

2024-07-17 23:13 UTC, kylebarron commented
Do you know why CI isn't running on this branch?

2024-07-17 23:42 UTC, michaelkirk commented
I do not know why CI isn't running for your branch. Maybe related to the conflicts in the current branch? (working on those now)

2024-07-17 23:56 UTC, michaelkirk commented
Ok - conflicts resolved.

2024-07-18 00:10 UTC, michaelkirk requested changes

2024-07-18 00:10 UTC, michaelkirk commented on src/lib.rs
> +                "Z" => {
These should be case insensitive - see our matching elsewhere using `eq_ignore_ascii_case`

2024-07-18 00:10 UTC, michaelkirk commented on src/types/mod.rs
> +pub use self::dimension::Dimension;
Does this need to be public? It doesn't look like it's used in any public APIs.

2024-07-18 04:16 UTC, ariesdevil commented
So we now only support `POINT Z`, and no longer support `POINTZ`?

2024-07-18 05:32 UTC, michaelkirk commented
That's correct. I don't ever use 3d points, but my understanding is that "POINT Z" is the correct spelling. Please let us know if you have compelling counter examples!

2024-07-18 16:04 UTC, michaelkirk approved these changes
Nice work, thanks @kylebarron!

2024-07-18 19:26 UTC, kylebarron commented
> So we now only support `POINT Z`, and no longer support `POINTZ`?

I added support for `POINTZ` (and `LINESTRINGZ` etc) in the latest commit. It does make the `match` statement kinda verbose; @michaelkirk what do you think?

2024-07-18 19:40 UTC, michaelkirk commented
Sure, since there is apparently some precedent for this spelling, I'm OK with (happy to?) support it. Thanks @kylebarron

2024-07-21 19:47 UTC, kylebarron commented
I had missed it but chapter 7 of https://www.ogc.org/standard/sfa/ does define WKT for geometries

2024-07-23 15:08 UTC, michaelkirk approved these changes

2024-07-23 15:10 UTC, merged